version: "3.9"

services:
  frontend:
    build:
      context: ./web-app
      dockerfile: Dockerfile.dev
    container_name: study-web
    ports:
      - "5173:5173" # Vite port
    volumes:
      - ./web-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn dev --host 0.0.0.0
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: study-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
